export enum TipoUsuarioEnum {
    FUNCIONARIO = 'FUNCIONARIO',
    CLIENTE = 'CLIENTE',
    USUARIO = 'USUARIO',
}

export enum TipoMoradorEnum {
    INQUILINO = 'INQUILINO',
    PREPONENTE1 = 'PREPONENTE1',
    PREPONENTE2 = 'PREPONENTE2',
    PREPONENTE3 = 'PREPONENTE3',
    REPASSE = 'REPASSE',
}